name: madcamp_week2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  flutter_sound: ^9.6.0
  http: ^0.13.3
  path_provider: ^2.0.11
  permission_handler: ^10.2.0  # 권한 요청 패키지 추가
  intl: ^0.17.0  # 날짜 형식을 위한 패키지 추가
  table_calendar: ^3.0.0  # 달력 기능을 위한 패키지 추가

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
